#!/bin/bash

if [ ! -d dist ]
then
    mkdir dist
fi

cat src/dollar_spec.js src/dollar_spec/matchers.js src/dollar_spec/verbs.js src/dollar_spec/spec.js src/vendor/stacktrace.js > dist/dollar_spec.js